### ISSUE TITLE
MoneroOcean

### ISSUE THREAD

**Issue by jweber018** [cryptoprofitswitcher/CryptonightProfitSwitcher#2]
Hey mate, just checked out your software and it's reaaaally cool. One addition I would make, would be using this pool: https://moneroocean.stream

It profit-switches between many cryptonight-v7 coins and pays you in Monero.

**Comment by cryptoprofitswitcher** [comment]
You can use whatever pool you like, you just need to set a coin's pool address to the pool. However the estimated profits would be wrong because the pool switches the mined coin itself. I need a way to get profitability data, so I opened an issue at https://github.com/MoneroOcean/nodejs-pool/issues/30

**Comment by cryptoprofitswitcher** [comment]
@jweber018 Try out the latest release V. 3.0.0 and look at https://github.com/cryptoprofitswitcher/CryptonightProfitSwitcher/blob/master/Coins/MoneroOcean.json
